### ISSUE TITLE
словарь -сделать автоподсказчик похожих слов 

### ISSUE THREAD

**Issue by tumanob** [tumanob/tili.kg#5]
с новой версткой не выпадает подсказки -  нужно исправить 

пример как должны работать подсказки при поиске слова:

при вводе слова после 2 символов выпадает подсказчик слов по алфавиту которые можно выбрать кликом мышки либо клавиатурой стрелками переходя по вариантам

http://www.oxforddictionaries.com/

http://www.oxfordlearnersdictionaries.com/definition/english/

![2015-10-17 4 18 47 pm](https://cloud.githubusercontent.com/assets/2038847/10558240/d4790e26-74ea-11e5-8671-e1969728d6b6.png)

**Comment by Entea** [comment]
@tumanob буду пилить завтра :)

**Comment by Entea** [comment]
@tumanob Переход стрелками не работает, пока тока клики

**Comment by tumanob** [comment]
@Entea изменил стил подсказок и сместил блок со спецсимволами.

**Comment by tumanob** [comment]
Добавил цвет фона в блок подсказки выделенного слова.
