### ISSUE TITLE
Настроить крон для удаления файлов сессий в  - ../data/mod-tmp

### ISSUE THREAD

**Issue by tumanob** [tumanob/tili.kg#6]
сейчас скапливается много файлов и они съедают место можно удалять их автоматически через крон.

**Comment by tumanob** [comment]
Зачистил логи на сервере. на строил параметры сборщика логов.

**Comment by Entea** [comment]
@tumanob ты настраивал logrotate или /etc/cron.d/php ?

**Comment by tumanob** [comment]
я в хостинг панеле настроил ограничения по логам и удалил все что накопилось. там  коло 8 гигов почистил от логов
