### ISSUE TITLE
после обновление jquery вылезает ошибки в bootstrap

### ISSUE THREAD

**Issue by tumanob** [tumanob/tili.kg#8]
из-за устаревших ссылок на $.browser котjрые были убраны в 1.9 -  bootstrap не работает   и часть плагинов jquery что в словаре отвалились.  нужно почистить и решить что вообще нужно что нет из js файлов

не работает 
- кнопка меню
- раскрывающуюся меня показывается сразу вместо показа попозже
- показ слова если оно выбрано не работает.  -  поиск слова работает в форме поиска в шапке. но вывода при клике в область нет.

провести рефакторинг JS для раздела словаря.  
чтобы дальше улучшать и менять. 

Сейчас раздел словаря после перевода на бутстрап и jquery 1.11 не работает

**Comment by tumanob** [comment]
jquery.ba-bbq.min.js   - проблема  в этом файле который устарел и не подходит для новой версии jquery

**Comment by Entea** [comment]
Fixed with pull request - https://github.com/tumanob/tili.kg/pull/11
