### ISSUE TITLE
в словаре  dict/  не появляется кнопка меню

### ISSUE THREAD

**Issue by tumanob** [tumanob/tili.kg#9]
В шапке у разделе словарей не показывается кнопка меню. на скрине показана кнопка на основном сайте wordpress.

![2016-02-14 1 09 02 pm](https://cloud.githubusercontent.com/assets/2038847/13032430/9653743e-d31c-11e5-9271-57db573b1f22.png)

**Comment by Entea** [comment]
Fixed with latest push to `material-design` branch
